# Default initial positions for the panda arm's ros2_control fake system
initial_positions:
  joint_1: 0.0
  joint_2: -0.7854
  joint_3: 0.0
  joint_4: 1.3962
  joint_5: 0.0
  joint_6: 0.6109
  joint_7: 0.0
