# Default initial positions for the panda arm's ros2_control fake system
initial_positions:
  iiwa7_joint_1: 0.0
  iiwa7_joint_2: -0.7854
  iiwa7_joint_3: 0.0
  iiwa7_joint_4: 1.3962
  iiwa7_joint_5: 0.0
  iiwa7_joint_6: 0.6109
  iiwa7_joint_7: 0.0
