# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    iiwa_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

iiwa_arm_controller:
  ros__parameters:
    joints:
      - iiwa7_joint_1
      - iiwa7_joint_2
      - iiwa7_joint_3
      - iiwa7_joint_4
      - iiwa7_joint_5
      - iiwa7_joint_6
      - iiwa7_joint_7
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity