name: C/C++ CI

on:
  push:
    branches: [ "ci_test" ]

jobs:
  ci_test:
    name: Testing ROS2 Environment
    runs-on: ubuntu-latest
    env:
      BUILD_DIR: colcon_ws

    steps:
      - uses: actions/checkout@v3
        with:
          path: ${{ github.workspace }}/${{ env.BUILD_DIR }}/src
      - name: My Action
        id: ros2
        uses: prachandabhanu/ros2-github-action2@main
        with:
          # image:  prachandabhanu/build_env:ros2-humble-kuka
          # options: -v /${{ env.BUILD_DIR }}/src:/${{ env.BUILD_DIR }}/src
          run: |
            ls
            cd /${{ env.BUILD_DIR }}/src
            ls
    

  ci_test_with_docker_image:
    name: Testing ROS2 Environment with Docker image
    needs: ci_test
    runs-on: ubuntu-latest
    env:
      BUILD_DIR: colcon_ws

    steps:
      - uses: actions/checkout@v3
        with:
          path: ${{ github.workspace }}/${{ env.BUILD_DIR }}/src
      - name: My Action
        id: ros2
        uses: prachandabhanu/ros2-github-action@main
        with:
          image:  prachandabhanu/build_env:ros2-humble-kuka
          options: -v /${{ env.BUILD_DIR }}/src:/${{ env.BUILD_DIR }}/src
          run: |
            ls
            cd /${{ env.BUILD_DIR }}/src
            ls

# cd /${{ env.BUILD_DIR }}/src