name: DeployDocumentation

on:
  push:
    branches:
      - main

jobs:
  deploy_documentation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Build Doxygen Documentation
        uses: mattnotmitt/doxygen-action@v1.9
        with:
            doxyfile-path: 'doxyfile.config'

      - name: Deploy Documentation
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          keep_files: false
